/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PERCENT_EQ_EQ = 1,
  anon_sym_PERCENT_EQ = 2,
  anon_sym_PERCENT_POUND = 3,
  anon_sym_PERCENT_PERCENT = 4,
  anon_sym_PERCENT = 5,
  anon_sym_LT = 6,
  anon_sym_LT_PERCENT_EQ_EQ = 7,
  anon_sym_LT_PERCENT_EQ = 8,
  anon_sym_LT_PERCENT_POUND = 9,
  anon_sym_LT_PERCENT = 10,
  sym_escaped_open_tag = 11,
  aux_sym_tag_content_token1 = 12,
  aux_sym_tag_content_token2 = 13,
  anon_sym_EQ = 14,
  anon_sym_PERCENT_GT = 15,
  sym_line_indent = 16,
  sym_line_content = 17,
  sym_text = 18,
  sym_non_directive_text = 19,
  sym_newline = 20,
  sym_source_file = 21,
  sym_directive_line = 22,
  sym_final_directive_line = 23,
  sym_line_statement = 24,
  sym_line_raw_expression = 25,
  sym_line_expression = 26,
  sym_line_comment = 27,
  sym_line_escaped_percent = 28,
  sym_line_code = 29,
  sym_content_line = 30,
  sym_final_content_line = 31,
  sym_whitespace_line = 32,
  sym__content_start = 33,
  sym__content_piece = 34,
  sym_tag = 35,
  sym_raw_expression_tag = 36,
  sym_expression_tag = 37,
  sym_comment_tag = 38,
  sym_code_tag = 39,
  sym_tag_content = 40,
  sym_tag_close = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_content_line_repeat1 = 43,
  aux_sym_tag_content_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT_EQ_EQ] = "%==",
  [anon_sym_PERCENT_EQ] = "%=",
  [anon_sym_PERCENT_POUND] = "%#",
  [anon_sym_PERCENT_PERCENT] = "%%",
  [anon_sym_PERCENT] = "%",
  [anon_sym_LT] = "<",
  [anon_sym_LT_PERCENT_EQ_EQ] = "<%==",
  [anon_sym_LT_PERCENT_EQ] = "<%=",
  [anon_sym_LT_PERCENT_POUND] = "<%#",
  [anon_sym_LT_PERCENT] = "<%",
  [sym_escaped_open_tag] = "escaped_open_tag",
  [aux_sym_tag_content_token1] = "tag_content_token1",
  [aux_sym_tag_content_token2] = "tag_content_token2",
  [anon_sym_EQ] = "=",
  [anon_sym_PERCENT_GT] = "%>",
  [sym_line_indent] = "line_indent",
  [sym_line_content] = "line_content",
  [sym_text] = "text",
  [sym_non_directive_text] = "non_directive_text",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym_directive_line] = "directive_line",
  [sym_final_directive_line] = "final_directive_line",
  [sym_line_statement] = "line_statement",
  [sym_line_raw_expression] = "line_raw_expression",
  [sym_line_expression] = "line_expression",
  [sym_line_comment] = "line_comment",
  [sym_line_escaped_percent] = "line_escaped_percent",
  [sym_line_code] = "line_code",
  [sym_content_line] = "content_line",
  [sym_final_content_line] = "final_content_line",
  [sym_whitespace_line] = "whitespace_line",
  [sym__content_start] = "_content_start",
  [sym__content_piece] = "_content_piece",
  [sym_tag] = "tag",
  [sym_raw_expression_tag] = "raw_expression_tag",
  [sym_expression_tag] = "expression_tag",
  [sym_comment_tag] = "comment_tag",
  [sym_code_tag] = "code_tag",
  [sym_tag_content] = "tag_content",
  [sym_tag_close] = "tag_close",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_content_line_repeat1] = "content_line_repeat1",
  [aux_sym_tag_content_repeat1] = "tag_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT_EQ_EQ] = anon_sym_PERCENT_EQ_EQ,
  [anon_sym_PERCENT_EQ] = anon_sym_PERCENT_EQ,
  [anon_sym_PERCENT_POUND] = anon_sym_PERCENT_POUND,
  [anon_sym_PERCENT_PERCENT] = anon_sym_PERCENT_PERCENT,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_PERCENT_EQ_EQ] = anon_sym_LT_PERCENT_EQ_EQ,
  [anon_sym_LT_PERCENT_EQ] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT_POUND] = anon_sym_LT_PERCENT_POUND,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT,
  [sym_escaped_open_tag] = sym_escaped_open_tag,
  [aux_sym_tag_content_token1] = aux_sym_tag_content_token1,
  [aux_sym_tag_content_token2] = aux_sym_tag_content_token2,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [sym_line_indent] = sym_line_indent,
  [sym_line_content] = sym_line_content,
  [sym_text] = sym_text,
  [sym_non_directive_text] = sym_non_directive_text,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym_directive_line] = sym_directive_line,
  [sym_final_directive_line] = sym_final_directive_line,
  [sym_line_statement] = sym_line_statement,
  [sym_line_raw_expression] = sym_line_raw_expression,
  [sym_line_expression] = sym_line_expression,
  [sym_line_comment] = sym_line_comment,
  [sym_line_escaped_percent] = sym_line_escaped_percent,
  [sym_line_code] = sym_line_code,
  [sym_content_line] = sym_content_line,
  [sym_final_content_line] = sym_final_content_line,
  [sym_whitespace_line] = sym_whitespace_line,
  [sym__content_start] = sym__content_start,
  [sym__content_piece] = sym__content_piece,
  [sym_tag] = sym_tag,
  [sym_raw_expression_tag] = sym_raw_expression_tag,
  [sym_expression_tag] = sym_expression_tag,
  [sym_comment_tag] = sym_comment_tag,
  [sym_code_tag] = sym_code_tag,
  [sym_tag_content] = sym_tag_content,
  [sym_tag_close] = sym_tag_close,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_content_line_repeat1] = aux_sym_content_line_repeat1,
  [aux_sym_tag_content_repeat1] = aux_sym_tag_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_escaped_open_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tag_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_content_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_line_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_line_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_non_directive_text] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_line] = {
    .visible = true,
    .named = true,
  },
  [sym_final_directive_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_line_raw_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_line_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_escaped_percent] = {
    .visible = true,
    .named = true,
  },
  [sym_line_code] = {
    .visible = true,
    .named = true,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_final_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_whitespace_line] = {
    .visible = true,
    .named = true,
  },
  [sym__content_start] = {
    .visible = false,
    .named = true,
  },
  [sym__content_piece] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_expression_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_code_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_close] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_code = 1,
  field_text = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_code] = "code",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_code, 1},
  [1] =
    {field_text, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 41,
  [52] = 35,
  [53] = 42,
  [54] = 54,
  [55] = 43,
  [56] = 38,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '\n', 28,
        '\r', 25,
        '%', 17,
        '<', 27,
        '=', 36,
        '\t', 26,
        ' ', 26,
        0x0b, 28,
        '\f', 28,
      );
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(4);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(31);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '%') ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '%') ADVANCE(35);
      END_STATE();
    case 8:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 9:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '<') ADVANCE(18);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == '%') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PERCENT_EQ_EQ);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PERCENT_EQ);
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PERCENT_POUND);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PERCENT_PERCENT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '%') ADVANCE(16);
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '%') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '%') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ);
      if (lookahead == '=') ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_POUND);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '%') ADVANCE(24);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_escaped_open_tag);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead == '<') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (('\n' <= lookahead && lookahead <= '\r')) ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(36);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_tag_content_token2);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_line_indent);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '%') ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_line_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == '%') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '<') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_non_directive_text);
      if (lookahead == '%') ADVANCE(37);
      if (lookahead == '<') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_non_directive_text);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 11},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 11},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 11},
  [42] = {.lex_state = 11},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 11},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT_EQ_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_POUND] = ACTIONS(1),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(1),
    [anon_sym_LT_PERCENT] = ACTIONS(1),
    [sym_escaped_open_tag] = ACTIONS(1),
    [aux_sym_tag_content_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_line_indent] = ACTIONS(1),
    [sym_non_directive_text] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym_directive_line] = STATE(2),
    [sym_final_directive_line] = STATE(59),
    [sym_line_statement] = STATE(50),
    [sym_line_raw_expression] = STATE(54),
    [sym_line_expression] = STATE(54),
    [sym_line_comment] = STATE(54),
    [sym_line_escaped_percent] = STATE(54),
    [sym_line_code] = STATE(54),
    [sym_content_line] = STATE(2),
    [sym_final_content_line] = STATE(59),
    [sym_whitespace_line] = STATE(2),
    [sym__content_start] = STATE(8),
    [sym_tag] = STATE(8),
    [sym_raw_expression_tag] = STATE(18),
    [sym_expression_tag] = STATE(18),
    [sym_comment_tag] = STATE(18),
    [sym_code_tag] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PERCENT_EQ_EQ] = ACTIONS(5),
    [anon_sym_PERCENT_EQ] = ACTIONS(7),
    [anon_sym_PERCENT_POUND] = ACTIONS(9),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(21),
    [anon_sym_LT_PERCENT] = ACTIONS(23),
    [sym_escaped_open_tag] = ACTIONS(25),
    [sym_line_indent] = ACTIONS(27),
    [sym_non_directive_text] = ACTIONS(25),
    [sym_newline] = ACTIONS(29),
  },
  [STATE(2)] = {
    [sym_directive_line] = STATE(3),
    [sym_final_directive_line] = STATE(58),
    [sym_line_statement] = STATE(50),
    [sym_line_raw_expression] = STATE(54),
    [sym_line_expression] = STATE(54),
    [sym_line_comment] = STATE(54),
    [sym_line_escaped_percent] = STATE(54),
    [sym_line_code] = STATE(54),
    [sym_content_line] = STATE(3),
    [sym_final_content_line] = STATE(58),
    [sym_whitespace_line] = STATE(3),
    [sym__content_start] = STATE(8),
    [sym_tag] = STATE(8),
    [sym_raw_expression_tag] = STATE(18),
    [sym_expression_tag] = STATE(18),
    [sym_comment_tag] = STATE(18),
    [sym_code_tag] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_PERCENT_EQ_EQ] = ACTIONS(5),
    [anon_sym_PERCENT_EQ] = ACTIONS(7),
    [anon_sym_PERCENT_POUND] = ACTIONS(9),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(21),
    [anon_sym_LT_PERCENT] = ACTIONS(23),
    [sym_escaped_open_tag] = ACTIONS(25),
    [sym_line_indent] = ACTIONS(33),
    [sym_non_directive_text] = ACTIONS(25),
    [sym_newline] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym_directive_line] = STATE(3),
    [sym_line_statement] = STATE(62),
    [sym_line_raw_expression] = STATE(54),
    [sym_line_expression] = STATE(54),
    [sym_line_comment] = STATE(54),
    [sym_line_escaped_percent] = STATE(54),
    [sym_line_code] = STATE(54),
    [sym_content_line] = STATE(3),
    [sym_whitespace_line] = STATE(3),
    [sym__content_start] = STATE(10),
    [sym_tag] = STATE(10),
    [sym_raw_expression_tag] = STATE(18),
    [sym_expression_tag] = STATE(18),
    [sym_comment_tag] = STATE(18),
    [sym_code_tag] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_PERCENT_EQ_EQ] = ACTIONS(39),
    [anon_sym_PERCENT_EQ] = ACTIONS(42),
    [anon_sym_PERCENT_POUND] = ACTIONS(45),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(48),
    [anon_sym_PERCENT] = ACTIONS(51),
    [anon_sym_LT] = ACTIONS(54),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(57),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(60),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(63),
    [anon_sym_LT_PERCENT] = ACTIONS(66),
    [sym_escaped_open_tag] = ACTIONS(69),
    [sym_line_indent] = ACTIONS(72),
    [sym_non_directive_text] = ACTIONS(69),
    [sym_newline] = ACTIONS(75),
  },
  [STATE(4)] = {
    [sym_line_statement] = STATE(47),
    [sym_line_raw_expression] = STATE(54),
    [sym_line_expression] = STATE(54),
    [sym_line_comment] = STATE(54),
    [sym_line_escaped_percent] = STATE(54),
    [sym_line_code] = STATE(54),
    [sym_tag] = STATE(21),
    [sym_raw_expression_tag] = STATE(18),
    [sym_expression_tag] = STATE(18),
    [sym_comment_tag] = STATE(18),
    [sym_code_tag] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(78),
    [anon_sym_PERCENT_EQ_EQ] = ACTIONS(5),
    [anon_sym_PERCENT_EQ] = ACTIONS(7),
    [anon_sym_PERCENT_POUND] = ACTIONS(9),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(80),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(21),
    [anon_sym_LT_PERCENT] = ACTIONS(23),
    [sym_escaped_open_tag] = ACTIONS(82),
    [sym_newline] = ACTIONS(84),
  },
  [STATE(5)] = {
    [sym_line_statement] = STATE(47),
    [sym_line_raw_expression] = STATE(54),
    [sym_line_expression] = STATE(54),
    [sym_line_comment] = STATE(54),
    [sym_line_escaped_percent] = STATE(54),
    [sym_line_code] = STATE(54),
    [sym_tag] = STATE(21),
    [sym_raw_expression_tag] = STATE(18),
    [sym_expression_tag] = STATE(18),
    [sym_comment_tag] = STATE(18),
    [sym_code_tag] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_PERCENT_EQ_EQ] = ACTIONS(5),
    [anon_sym_PERCENT_EQ] = ACTIONS(7),
    [anon_sym_PERCENT_POUND] = ACTIONS(9),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(80),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(21),
    [anon_sym_LT_PERCENT] = ACTIONS(23),
    [sym_escaped_open_tag] = ACTIONS(82),
    [sym_newline] = ACTIONS(84),
  },
  [STATE(6)] = {
    [sym_line_statement] = STATE(61),
    [sym_line_raw_expression] = STATE(54),
    [sym_line_expression] = STATE(54),
    [sym_line_comment] = STATE(54),
    [sym_line_escaped_percent] = STATE(54),
    [sym_line_code] = STATE(54),
    [sym_tag] = STATE(21),
    [sym_raw_expression_tag] = STATE(18),
    [sym_expression_tag] = STATE(18),
    [sym_comment_tag] = STATE(18),
    [sym_code_tag] = STATE(18),
    [anon_sym_PERCENT_EQ_EQ] = ACTIONS(86),
    [anon_sym_PERCENT_EQ] = ACTIONS(88),
    [anon_sym_PERCENT_POUND] = ACTIONS(90),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(92),
    [anon_sym_PERCENT] = ACTIONS(94),
    [anon_sym_LT] = ACTIONS(80),
    [anon_sym_LT_PERCENT_EQ_EQ] = ACTIONS(17),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(21),
    [anon_sym_LT_PERCENT] = ACTIONS(23),
    [sym_escaped_open_tag] = ACTIONS(82),
    [sym_newline] = ACTIONS(84),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      anon_sym_LT_PERCENT_EQ_EQ,
    ACTIONS(19), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(23), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 1,
      sym_newline,
    ACTIONS(98), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(100), 2,
      sym_escaped_open_tag,
      sym_non_directive_text,
    STATE(9), 3,
      sym__content_piece,
      sym_tag,
      aux_sym_content_line_repeat1,
    STATE(18), 4,
      sym_raw_expression_tag,
      sym_expression_tag,
      sym_comment_tag,
      sym_code_tag,
  [38] = 10,
    ACTIONS(17), 1,
      anon_sym_LT_PERCENT_EQ_EQ,
    ACTIONS(19), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(23), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 1,
      sym_newline,
    ACTIONS(106), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(108), 2,
      sym_escaped_open_tag,
      sym_non_directive_text,
    STATE(7), 3,
      sym__content_piece,
      sym_tag,
      aux_sym_content_line_repeat1,
    STATE(18), 4,
      sym_raw_expression_tag,
      sym_expression_tag,
      sym_comment_tag,
      sym_code_tag,
  [76] = 9,
    ACTIONS(117), 1,
      anon_sym_LT_PERCENT_EQ_EQ,
    ACTIONS(120), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(123), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(126), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym_newline,
    ACTIONS(114), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(129), 2,
      sym_escaped_open_tag,
      sym_non_directive_text,
    STATE(9), 3,
      sym__content_piece,
      sym_tag,
      aux_sym_content_line_repeat1,
    STATE(18), 4,
      sym_raw_expression_tag,
      sym_expression_tag,
      sym_comment_tag,
      sym_code_tag,
  [112] = 9,
    ACTIONS(17), 1,
      anon_sym_LT_PERCENT_EQ_EQ,
    ACTIONS(19), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(23), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(110), 1,
      sym_newline,
    ACTIONS(132), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(134), 2,
      sym_escaped_open_tag,
      sym_non_directive_text,
    STATE(11), 3,
      sym__content_piece,
      sym_tag,
      aux_sym_content_line_repeat1,
    STATE(18), 4,
      sym_raw_expression_tag,
      sym_expression_tag,
      sym_comment_tag,
      sym_code_tag,
  [147] = 9,
    ACTIONS(17), 1,
      anon_sym_LT_PERCENT_EQ_EQ,
    ACTIONS(19), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(23), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(102), 1,
      sym_newline,
    ACTIONS(98), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(100), 2,
      sym_escaped_open_tag,
      sym_non_directive_text,
    STATE(9), 3,
      sym__content_piece,
      sym_tag,
      aux_sym_content_line_repeat1,
    STATE(18), 4,
      sym_raw_expression_tag,
      sym_expression_tag,
      sym_comment_tag,
      sym_code_tag,
  [182] = 2,
    ACTIONS(138), 6,
      anon_sym_PERCENT_EQ,
      anon_sym_PERCENT,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_line_indent,
    ACTIONS(136), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_EQ_EQ,
      anon_sym_PERCENT_POUND,
      anon_sym_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [202] = 2,
    ACTIONS(142), 6,
      anon_sym_PERCENT_EQ,
      anon_sym_PERCENT,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_line_indent,
    ACTIONS(140), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_EQ_EQ,
      anon_sym_PERCENT_POUND,
      anon_sym_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [222] = 2,
    ACTIONS(146), 6,
      anon_sym_PERCENT_EQ,
      anon_sym_PERCENT,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_line_indent,
    ACTIONS(144), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_EQ_EQ,
      anon_sym_PERCENT_POUND,
      anon_sym_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [242] = 2,
    ACTIONS(150), 6,
      anon_sym_PERCENT_EQ,
      anon_sym_PERCENT,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_line_indent,
    ACTIONS(148), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_EQ_EQ,
      anon_sym_PERCENT_POUND,
      anon_sym_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [262] = 2,
    ACTIONS(154), 6,
      anon_sym_PERCENT_EQ,
      anon_sym_PERCENT,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_line_indent,
    ACTIONS(152), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_EQ_EQ,
      anon_sym_PERCENT_POUND,
      anon_sym_PERCENT_PERCENT,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [282] = 2,
    ACTIONS(158), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(156), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [297] = 2,
    ACTIONS(162), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [312] = 2,
    ACTIONS(166), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [327] = 2,
    ACTIONS(170), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [342] = 2,
    ACTIONS(174), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [357] = 2,
    ACTIONS(178), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(176), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [372] = 2,
    ACTIONS(182), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(180), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [387] = 2,
    ACTIONS(186), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(184), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [402] = 2,
    ACTIONS(190), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(188), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [417] = 2,
    ACTIONS(194), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(192), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [432] = 2,
    ACTIONS(198), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(196), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [447] = 2,
    ACTIONS(202), 4,
      anon_sym_LT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      sym_text,
    ACTIONS(200), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ_EQ,
      anon_sym_LT_PERCENT_POUND,
      sym_escaped_open_tag,
      sym_non_directive_text,
      sym_newline,
  [462] = 6,
    ACTIONS(206), 1,
      anon_sym_EQ,
    ACTIONS(208), 1,
      anon_sym_PERCENT_GT,
    STATE(22), 1,
      sym_tag_close,
    STATE(33), 1,
      aux_sym_tag_content_repeat1,
    STATE(40), 1,
      sym_tag_content,
    ACTIONS(204), 2,
      aux_sym_tag_content_token1,
      aux_sym_tag_content_token2,
  [482] = 6,
    ACTIONS(206), 1,
      anon_sym_EQ,
    ACTIONS(208), 1,
      anon_sym_PERCENT_GT,
    STATE(23), 1,
      sym_tag_close,
    STATE(33), 1,
      aux_sym_tag_content_repeat1,
    STATE(39), 1,
      sym_tag_content,
    ACTIONS(204), 2,
      aux_sym_tag_content_token1,
      aux_sym_tag_content_token2,
  [502] = 6,
    ACTIONS(206), 1,
      anon_sym_EQ,
    ACTIONS(208), 1,
      anon_sym_PERCENT_GT,
    STATE(24), 1,
      sym_tag_close,
    STATE(33), 1,
      aux_sym_tag_content_repeat1,
    STATE(37), 1,
      sym_tag_content,
    ACTIONS(204), 2,
      aux_sym_tag_content_token1,
      aux_sym_tag_content_token2,
  [522] = 6,
    ACTIONS(206), 1,
      anon_sym_EQ,
    ACTIONS(208), 1,
      anon_sym_PERCENT_GT,
    STATE(20), 1,
      sym_tag_close,
    STATE(33), 1,
      aux_sym_tag_content_repeat1,
    STATE(36), 1,
      sym_tag_content,
    ACTIONS(204), 2,
      aux_sym_tag_content_token1,
      aux_sym_tag_content_token2,
  [542] = 4,
    ACTIONS(212), 1,
      anon_sym_EQ,
    ACTIONS(214), 1,
      anon_sym_PERCENT_GT,
    STATE(34), 1,
      aux_sym_tag_content_repeat1,
    ACTIONS(210), 2,
      aux_sym_tag_content_token1,
      aux_sym_tag_content_token2,
  [556] = 4,
    ACTIONS(219), 1,
      anon_sym_EQ,
    ACTIONS(221), 1,
      anon_sym_PERCENT_GT,
    STATE(34), 1,
      aux_sym_tag_content_repeat1,
    ACTIONS(216), 2,
      aux_sym_tag_content_token1,
      aux_sym_tag_content_token2,
  [570] = 2,
    ACTIONS(225), 1,
      sym_line_content,
    ACTIONS(223), 2,
      ts_builtin_sym_end,
      sym_newline,
  [578] = 3,
    ACTIONS(208), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(227), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_tag_close,
  [588] = 3,
    ACTIONS(208), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(227), 1,
      anon_sym_EQ,
    STATE(17), 1,
      sym_tag_close,
  [598] = 2,
    ACTIONS(231), 1,
      sym_line_content,
    ACTIONS(229), 2,
      ts_builtin_sym_end,
      sym_newline,
  [606] = 3,
    ACTIONS(208), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(227), 1,
      anon_sym_EQ,
    STATE(28), 1,
      sym_tag_close,
  [616] = 3,
    ACTIONS(208), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(227), 1,
      anon_sym_EQ,
    STATE(27), 1,
      sym_tag_close,
  [626] = 2,
    ACTIONS(235), 1,
      sym_line_content,
    ACTIONS(233), 2,
      ts_builtin_sym_end,
      sym_newline,
  [634] = 2,
    ACTIONS(239), 1,
      sym_line_content,
    ACTIONS(237), 2,
      ts_builtin_sym_end,
      sym_newline,
  [642] = 2,
    ACTIONS(243), 1,
      sym_line_content,
    ACTIONS(241), 2,
      ts_builtin_sym_end,
      sym_newline,
  [650] = 1,
    ACTIONS(245), 2,
      ts_builtin_sym_end,
      sym_newline,
  [655] = 1,
    ACTIONS(247), 2,
      ts_builtin_sym_end,
      sym_newline,
  [660] = 1,
    ACTIONS(249), 2,
      ts_builtin_sym_end,
      sym_newline,
  [665] = 2,
    ACTIONS(251), 1,
      ts_builtin_sym_end,
    ACTIONS(253), 1,
      sym_newline,
  [672] = 1,
    ACTIONS(255), 2,
      ts_builtin_sym_end,
      sym_newline,
  [677] = 1,
    ACTIONS(257), 2,
      ts_builtin_sym_end,
      sym_newline,
  [682] = 2,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
    ACTIONS(261), 1,
      sym_newline,
  [689] = 2,
    ACTIONS(233), 1,
      sym_newline,
    ACTIONS(235), 1,
      sym_line_content,
  [696] = 2,
    ACTIONS(223), 1,
      sym_newline,
    ACTIONS(225), 1,
      sym_line_content,
  [703] = 2,
    ACTIONS(237), 1,
      sym_newline,
    ACTIONS(239), 1,
      sym_line_content,
  [710] = 1,
    ACTIONS(263), 2,
      ts_builtin_sym_end,
      sym_newline,
  [715] = 2,
    ACTIONS(241), 1,
      sym_newline,
    ACTIONS(243), 1,
      sym_line_content,
  [722] = 2,
    ACTIONS(229), 1,
      sym_newline,
    ACTIONS(231), 1,
      sym_line_content,
  [729] = 1,
    ACTIONS(265), 1,
      anon_sym_PERCENT_GT,
  [733] = 1,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
  [737] = 1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
  [741] = 1,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
  [745] = 1,
    ACTIONS(253), 1,
      sym_newline,
  [749] = 1,
    ACTIONS(261), 1,
      sym_newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 38,
  [SMALL_STATE(9)] = 76,
  [SMALL_STATE(10)] = 112,
  [SMALL_STATE(11)] = 147,
  [SMALL_STATE(12)] = 182,
  [SMALL_STATE(13)] = 202,
  [SMALL_STATE(14)] = 222,
  [SMALL_STATE(15)] = 242,
  [SMALL_STATE(16)] = 262,
  [SMALL_STATE(17)] = 282,
  [SMALL_STATE(18)] = 297,
  [SMALL_STATE(19)] = 312,
  [SMALL_STATE(20)] = 327,
  [SMALL_STATE(21)] = 342,
  [SMALL_STATE(22)] = 357,
  [SMALL_STATE(23)] = 372,
  [SMALL_STATE(24)] = 387,
  [SMALL_STATE(25)] = 402,
  [SMALL_STATE(26)] = 417,
  [SMALL_STATE(27)] = 432,
  [SMALL_STATE(28)] = 447,
  [SMALL_STATE(29)] = 462,
  [SMALL_STATE(30)] = 482,
  [SMALL_STATE(31)] = 502,
  [SMALL_STATE(32)] = 522,
  [SMALL_STATE(33)] = 542,
  [SMALL_STATE(34)] = 556,
  [SMALL_STATE(35)] = 570,
  [SMALL_STATE(36)] = 578,
  [SMALL_STATE(37)] = 588,
  [SMALL_STATE(38)] = 598,
  [SMALL_STATE(39)] = 606,
  [SMALL_STATE(40)] = 616,
  [SMALL_STATE(41)] = 626,
  [SMALL_STATE(42)] = 634,
  [SMALL_STATE(43)] = 642,
  [SMALL_STATE(44)] = 650,
  [SMALL_STATE(45)] = 655,
  [SMALL_STATE(46)] = 660,
  [SMALL_STATE(47)] = 665,
  [SMALL_STATE(48)] = 672,
  [SMALL_STATE(49)] = 677,
  [SMALL_STATE(50)] = 682,
  [SMALL_STATE(51)] = 689,
  [SMALL_STATE(52)] = 696,
  [SMALL_STATE(53)] = 703,
  [SMALL_STATE(54)] = 710,
  [SMALL_STATE(55)] = 715,
  [SMALL_STATE(56)] = 722,
  [SMALL_STATE(57)] = 729,
  [SMALL_STATE(58)] = 733,
  [SMALL_STATE(59)] = 737,
  [SMALL_STATE(60)] = 741,
  [SMALL_STATE(61)] = 745,
  [SMALL_STATE(62)] = 749,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_final_content_line, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_final_content_line, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whitespace_line, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_whitespace_line, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_line, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_line, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_line, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_line, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_line, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_line, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_tag, 3, 0, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_tag, 3, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_close, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_close, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_expression_tag, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_expression_tag, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__content_start, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__content_start, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_tag, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_tag, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_tag, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_tag, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_tag, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_tag, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_close, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_close, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_expression_tag, 3, 0, 1),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_expression_tag, 3, 0, 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_tag, 3, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_tag, 3, 0, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_tag, 3, 0, 2),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_tag, 3, 0, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_content, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_content, 1, 0, 0),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_content_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_content_repeat1, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_content_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_code, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_raw_expression, 1, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_expression, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_escaped_percent, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_escaped_percent, 2, 0, 2),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 2),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_code, 2, 0, 1),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_final_directive_line, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_raw_expression, 2, 0, 1),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_expression, 2, 0, 1),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_final_directive_line, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_statement, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [267] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_embedded_perl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "embedded_perl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
